# Generated by Django 3.2.14 on 2022-07-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_product', models.IntegerField()),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(choices=[('P', 'Pending Payment'), ('T', 'Out for Delivery'), ('D', 'Delivered')], default='Pending', max_length=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.product')),
            ],
            options={
                'verbose_name': 'Order Item',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
