# Generated by Django 3.2.14 on 2022-07-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20220728_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
