name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: linux-runner
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
          python-version: "3.11.0-beta.5"
          architecture: "x64"
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

          
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install django-debug-toolbar
        pip install factory_boy   
        pip install psycopg2-binary
        pip install django-extensions
        pip install pytest
        
    - name: Run Tests
      run: |
        python manage.py test
